name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 2.2.1
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: poetry-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Install dependencies
      working-directory: ./src
      run: poetry install
    
    - name: Run tests
      working-directory: ./src
      run: poetry run pytest tests/ -v --tb=short
    
    - name: Test Docker build
      working-directory: ./src
      run: |
        docker build -t fastapi-app:test .
        docker run --rm -d --name test-app -p 8000:8000 fastapi-app:test
        sleep 10
        curl -f http://localhost:8000/healthy || exit 1
        curl -f http://localhost:8000/generate || exit 1
        docker stop test-app